export const environment = {
  production: true,
  apiKey:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOGQxOWYwMS00MDQ4LTRjZTAtODg2NS1mMGVkNGExZDBhNjIiLCJlbWFpbCI6ImZlbGlwZW1haW5lczEyM0BnbWFpbC5jb20iLCJnaXZlbl9uYW1lIjoiRmVsaXBlIiwibmJmIjoxNjk3NDc1ODQ1LCJleHAiOjE2OTc1MDQ2NDUsImlhdCI6MTY5NzQ3NTg0NSwiaXNzIjoiZUFnZW5kYSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3QifQ.nRbgMDEvomK_Jf0rw-0jMzTcWjg4ubGGrWi0xAZyhXs',
};
