export const environment = {
  production: true,
  apiKey:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOGQxOWYwMS00MDQ4LTRjZTAtODg2NS1mMGVkNGExZDBhNjIiLCJlbWFpbCI6ImZlbGlwZW1haW5lczEyM0BnbWFpbC5jb20iLCJnaXZlbl9uYW1lIjoiRmVsaXBlIiwibmJmIjoxNjk2NzkyMTEzLCJleHAiOjE2OTY4MjA5MTMsImlhdCI6MTY5Njc5MjExMywiaXNzIjoiZUFnZW5kYSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3QifQ.n4WaA_UdMfsMlcD3kvI8MaFahzQESvCdM2esDIPRLd8',
};
