export const environment = {
  production: true,
  apiKey:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOGQxOWYwMS00MDQ4LTRjZTAtODg2NS1mMGVkNGExZDBhNjIiLCJlbWFpbCI6ImZlbGlwZW1haW5lczEyM0BnbWFpbC5jb20iLCJnaXZlbl9uYW1lIjoiRmVsaXBlIiwibmJmIjoxNjk2OTYwMDExLCJleHAiOjE2OTY5ODg4MTEsImlhdCI6MTY5Njk2MDAxMSwiaXNzIjoiZUFnZW5kYSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3QifQ.KEjbMKgZM6jmrp4uofOCeXcMri1zEv6eF7ibIGh2CRE',
};
